# Generated by Django 4.0.6 on 2022-08-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='category',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='category'),
        ),
    ]
