# Generated by Django 4.0.6 on 2022-08-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='phone'),
        ),
    ]
