# Generated by Django 4.0.6 on 2022-07-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deleted_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='delete date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modified_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='modification date'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='created_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='deleted_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='delete date'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='modified_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='modification date'),
        ),
    ]
