# Generated by Django 4.0.6 on 2022-08-08 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0002_alter_employee_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_per_hour',
            field=models.FloatField(default=None, max_length=255, verbose_name='salary'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='salary_per_hour',
            field=models.FloatField(default=None, max_length=255, verbose_name='salary'),
        ),
    ]
