# Generated by Django 4.0.6 on 2022-08-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=255, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='role',
            field=models.CharField(max_length=255, null=True, verbose_name='role'),
        ),
    ]
