# Generated by Django 4.0.6 on 2022-08-09 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0011_employee_role_historicalemployee_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAttendance',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('date', models.DateField(verbose_name='date')),
                ('entrance_time', models.DateTimeField(verbose_name='entrance_time')),
                ('exit_time', models.DateTimeField(default=None, null=True, verbose_name='exit_time')),
                ('hours_worked', models.FloatField(default=None, max_length=255, null=True, verbose_name='hours_worked')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Attendance',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('entrance_time', models.DateTimeField(verbose_name='entrance_time')),
                ('exit_time', models.DateTimeField(default=None, null=True, verbose_name='exit_time')),
                ('hours_worked', models.FloatField(default=None, max_length=255, null=True, verbose_name='hours_worked')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
    ]
